[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
license = "MIT"
name = "boxcars"
readme = "README.md"
repository = "https://github.com/nickbabcock/boxcars"
description = "Rocket league replay parser"
keywords = ["rocket-league"]
categories = ["parsing"]
version = "0.2.6"
include = ["src/**/*.rs", "Cargo.toml", "build.rs"]

[dependencies]
serde = "1"
serde_derive = "1"
failure = "0.1.1"
encoding_rs = "0.7"
byteorder = "1"
phf = "0.7"
fnv = "1.0"
if_chain = "0.1"
bitter = "0.3.1"
multimap = "0.4"

[dev-dependencies]
serde_json = "1"
criterion = "0.2"

[[bench]]
name = "bench_boxcars"
harness = false

[build-dependencies]
phf_codegen = "0.7"

[workspace]
members = ["rrrocket"]
