[package]
name = "boxcars"
version = "0.1.0"
authors = ["nick"]
build = "build.rs"

[features]
default = ["serde_codegen"]
nightly = ["serde_derive"]

[build-dependencies]
serde_codegen = { version = "^0.8.12", optional = true }

[dependencies]
nom = "^1.2.4"
encoding = "0.2.33"
serde = "^0.8.12"
serde_derive = { version = "^0.8.12", optional = true }

# Include serde_json for our cli. Unfortunately there are currently no ways to
# specify dependencies just for our cli:
# https://github.com/rust-lang/cargo/issues/1982
# Since this is really only an example repo, I won't worry about creating a
# separate `bin` cargo file
serde_json = "0.8"
