[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
license = "MIT"
name = "boxcars"
readme = "README.md"
repository = "https://github.com/nickbabcock/boxcars"
version = "0.1.0"

[dependencies]
serde = "1"
serde_derive = "1"
failure = "0.1.1"
encoding_rs = "0.7"
byteorder = "1"

[dev-dependencies]
serde_json = "1"

[workspace]
members = ["rrrocket"]

[profile.bench]
debug = true
