[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
license = "MIT"
name = "boxcars"
readme = "README.md"
repository = "https://github.com/nickbabcock/boxcars"
version = "0.1.0"

[dependencies]
encoding = "0.2.33"
error-chain = "0.11.0"
serde = "1.0.18"
serde_derive = "1.0.18"

[dependencies.nom]
features = ["verbose-errors"]
version = "3.2.1"

[dev-dependencies]
serde_json = "1.0.5"

[workspace]
members = ["rrrocket"]
