[package]
authors = ["nick"]
name = "boxcars"
version = "0.1.0"

[dependencies]
encoding = "0.2.33"
serde = "1.0.16"
serde_derive = "1.0.16"
serde_json = "1.0.4"

[dependencies.nom]
features = ["verbose-errors"]
version = "3.2.0"
