[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
name = "boxcars"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/nickbabcock/boxcars"
readme = "README.md"

[dependencies]
encoding = "0.2.33"
serde = "1.0.16"
serde_derive = "1.0.16"

[dependencies.nom]
features = ["verbose-errors"]
version = "3.2.0"

[dev-dependencies]
serde_json = "1.0.4"
