[package]
name = "boxcars-web"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
boxcars = "0.2"
wasm-bindgen = { git = 'https://github.com/alexcrichton/wasm-bindgen' }
